---
title: "Statewide Kendall's Taus Extractor"
author: "Lilian Ngweta"
date: "09/27/2019"
output: html_notebook
---
Note: Re-used code written by: Yuxuan Wang, Shengjin Li, and Ziyi Wang



Reading Source.R
```{r}
source("Source.R")
```


Extracting Taus for all social determinants on nationwide data. The goal is to filter out social dterminants that are less relevant.
```{r}
state = "US"
# UNORDERED mortality trend cluster label calculation
mort.cluster.raw <- function(){
  
  # Variables:
  #   - county_fips
  #   - cluster
  
  # Currently hard-coded 4 clusters
  n.clusters <- 6
  cluster.counties(cdc.mort.mat(cdc.data, "US", "Despair"),
                   cluster.method="kmeans",
                   cluster.num=n.clusters)
}

# Weighed Avg by UNORDERED cluster
mort.avg.cluster.raw <- function(){
  
  # Variables:
  #   - period
  #   - cluster
  #   - death_rate
  #   - count
  
  # Notes:
  #   - The cluster labels are UNORDERED
  
  cdc.data %>%
    dplyr::filter(death_cause == "Despair") %>%
    dplyr::right_join(mort.cluster.raw(), by = "county_fips") %>%
    dplyr::group_by(period, cluster) %>%
    dplyr::summarise(
      death_rate = sum(death_num) / sum(population) * 10^5,
      count = n()
    ) %>% 
    dplyr::ungroup()
}

# MAPPING from UNORDERED mortality trend label to ORDERED mortality trend label
mort.cluster.map <- function(){
  
  # Variables:
  #   - ord
  
  # Notes:
  #   - This is a mapping from raw cluster label to ORDERED cluster.
  #       Row names are the original cluster and `ord` are the reordered cluster
  
  mort.avg.cluster.raw() %>% 
    dplyr::filter(period == "2015-2017") %>%
    dplyr::arrange(death_rate) %>% 
    dplyr::mutate(ord = as.character(1:n())) %>% 
    dplyr::select(-c(period, death_rate)) %>% 
    textshape::column_to_rownames("cluster")
}

# ORDERED mortality trend cluster label calculation
mort.cluster.ord <- function(){
  
  # Variables:
  #   - county_fips
  #   - cluster
  
  order.county.clusters(mort.cluster.raw(), mort.cluster.map())
  #dplyr::mutate(mort.cluster.raw(), cluster = mort.cluster.map()[cluster, "ord"])
}

# Weighed Avg by ORDERED cluster
mort.avg.cluster.ord <- function(){
  
  # Variables:
  #   - period
  #   - cluster
  #   - death_rate
  #   - count
  
  # Notes:
  #   - The cluster labels are ORDERED
  
  dplyr::mutate(mort.avg.cluster.raw(), cluster = mort.cluster.map()[cluster, "ord"])
}
#print(mort.cluster.ord())
# Kendall Correlation Between raw mortality rates and county health rankings social determinants
kendall.cor <- kendall.func(mort.cluster.ord(), chr.data.2019)
kendall.cor <- kendall.cor %>%
  dplyr::mutate(
    Direction = dplyr::if_else(
      kendall_cor <= 0,
      "Protective",
      "Destructive"
    ),
    #kendall_cor = abs(kendall_cor),
    kendall_cor = kendall_cor,
    chr_code = chr.namemap.2019[chr_code, 1]
  ) %>% na.omit() %>% 
  #kendall_p = p.adjust(kendall_p, method = p.adjust.methods, n = length(kendall_p)) %>% 
  dplyr::filter(kendall_p < 0.05) %>% 
  #dplyr::filter(p.adjust(kendall_p, method = p.adjust.methods, n = length(kendall_p))) %>% 
  dplyr::arrange(desc(kendall_cor))

selected_SDs2 <- cbind(kendall.cor, state = state)

#using Benjamin Hochberg's p.adjust() method to adjust P-values for multiple hypothesis testing
corrected_pvalues <- p.adjust(selected_SDs2$kendall_p)

selected_SDs2 <- cbind(selected_SDs2, Corrected_P_Vals = corrected_pvalues)

selected_SDs2 <- selected_SDs2 %>%
  #kendall_p = p.adjust(kendall_p, method = p.adjust.methods, n = length(kendall_p)) %>% 
  dplyr::filter(Corrected_P_Vals < 0.05) %>% 
  #dplyr::filter(p.adjust(kendall_p, method = p.adjust.methods, n = length(kendall_p))) %>% 
  dplyr::arrange(desc(kendall_cor))

# selected_SDs2[selected_SDs2$kendall_p == p.adjust(selected_SDs2$kendall_p),]
print(selected_SDs2)
```






