---
title: "COUNTY HEATH RANKINGS"
author: "Ziyi, Thilanka and Lilian"
date: "6/06/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing and Preparing social determinant data from RHI hub website
* Source Website: 
    * RHIhub
    * https://www.ruralhealthinfo.org/data-explorer?id=220&state=NY
    
* Source files:
  * Median Household income-NY 2009-2016
  *Poverty-NY 2009-2017
  *Unemployment Rate-NY 2007-2018
  
Note:*Low access to healthy food is only available for 2015
	

```{r }
# install and load libraries
if (!require("readxl")) {
  install.packages("readxl")
  library(readxl)
}

# install and load libraries
if (!require("tidyverse")) {
  install.packages("tidyverse")
  library(tidyverse)
}

```

```{r }
# Make sure we're in the right place:
setwd("~/data/AHRQ_Challenge/Datasets/COUNTYHEALTH")

```



```{r }
# 
# NOTE: Cleanup required due to headers!!
healthrankings<- read_excel("~/data/AHRQ_Challenge/Datasets/COUNTYHEALTH/2019CountyHealth.xls",sheet=2)

# First 8 rows are header; remove
healthrankings <- healthrankings[3:nrow(healthrankings),c(1,3,4,6)]

# Get the colnames so we can strategize how to split
colnames(healthrankings)<-c("FIPS","County","HealthOutcomesZscore","HealthFactorsZscore")
```

```{r }
# 
# NOTE: Cleanup required due to headers!!
healthsubrankings<- read_excel("~/data/AHRQ_Challenge/Datasets/COUNTYHEALTH/2019CountyHealth.xls",sheet=3)

# Desired columns are the zscores
healthsubrankings <- healthsubrankings[3:nrow(healthsubrankings),c(1,3,4,6,8,10,12,14)]


# Get the colnames so we can strategize how to split
colnames(healthsubrankings)<-c("FIPS","County","LengthofLife","QualityofLife","HealthBehaviors","ClinicalCare","SocioEconomic","PhysicalEnvironment") 
```

```{r }
# 
# NOTE: Cleanup required due to headers!!
healthmeasures<- read_excel("~/data/AHRQ_Challenge/Datasets/COUNTYHEALTH/2019CountyHealth.xls",sheet=5)

# Desired columns are the zscores
colnames(healthmeasures) <- healthmeasures[1,]

healthmeasures<-healthmeasures[3:nrow(healthmeasures),]
```

```{r }
# 
# NOTE: Cleanup required due to headers!!
healthrankmeasures<- read_excel("~/data/AHRQ_Challenge/Datasets/COUNTYHEALTH/2019CountyHealth.xls",sheet=4)

# Desired columns are the zscores
colnames(healthrankmeasures) <- healthrankmeasures[1,]

healthrankmeasures<-healthrankmeasures[3:nrow(healthrankmeasures),]
```

```{r }
CountyHealth<-cbind(healthrankings,healthsubrankings[,2:ncol(healthsubrankings)],healthmeasures[,2:ncol(healthsubrankings)])


# Save it!
saveRDS(CountyHealth, file="CountyHealthl.rds")


```


# Save it!
saveRDS(PopulationEstimates_final, file="PopulationEstimates_final.rds")


```

